### ISSUE TITLE
Interpolation error

### ISSUE THREAD

**Issue by xRoyBx** [iBobbyTS/VFIN#1]
Thih is my input:

!tar -xf /content/VFIN-1.0.1.tar
!mkdir /content/VFIN/DAIN/model_weights
!wget http://vllab1.ucmerced.edu/~wenbobao/DAIN/best.pth -o /content/VFIN/DAIN/model_weights/best.pth

%cd /content/VFIN
!/content/python/bin/python3 /content/VFIN/run.py -i "/content/drive/My Drive/VFIN/input.mp4" -a DAIN

Now i get this error:

/content/VFIN
Traceback (most recent call last):
  File "/content/VFIN/run.py", line 314, in <module>
    interpolator = Interpolator(cag['model_path'], cag['sf'], int(cag['height']), int(cag['width']), batch_size=1,
  File "/content/VFIN/DAIN/interpolator.py", line 25, in __init__
    pretrained_dict = {k: v for k, v in torch.load(model_directory).items() if k in model_dict}
  File "/content/python/lib/python3.8/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/content/python/lib/python3.8/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '-'.

**Comment by iBobbyTS** [comment]
This is probably caused by the incompleteness of the model, remove it and download it again

**Comment by iBobbyTS** [comment]
This notebook I just verified, DAIN works. [1.0.1.ipynb](https://colab.research.google.com/drive/1QJNHMqtyMQcLuAAp_O0-h0DUyR5m_Qvo?usp=sharing)

**Comment by xRoyBx** [comment]
> This notebook I just verified, DAIN works. [1.0.1.ipynb](https://colab.research.google.com/drive/1QJNHMqtyMQcLuAAp_O0-h0DUyR5m_Qvo?usp=sharing)

With this latest notebook i finally got it working. Thanks man!

**Comment by iBobbyTS** [comment]
Actually, thank you for reporting bug, when I'm writing the code, I don't feel these kinds of bug because I can figure them out easily. 
Now I finally have one version that will work. I'll be working on 1.0.2, fixing bugs and make new functions.
