### ISSUE TITLE
处理视频时无响应

### ISSUE THREAD

**Issue by Stardust-minus** [iBobbyTS/VFIN#3]
如题。
GPU为NVIDIA A100 80G。
使用miniconda环境，已安装ffmpeg,opencv-python。
使用conda安装了pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1
build过程中未报错。

![image](https://user-images.githubusercontent.com/52093397/172370252-0c218606-807d-4cfb-9180-628eefa6626f.png)

运行 python run.py -i ../731008375_nb2-1-80.flv -a DAIN -fps 120  后，程序启动但没有任何输出。
使用top看到此时程序使用了约100%的CPU，nvidia-smi显示其只占用了几百M的显存。
![image](https://user-images.githubusercontent.com/52093397/172370472-8e3b9515-e42d-41ba-8dc3-f46e1984ad00.png)
![image](https://user-images.githubusercontent.com/52093397/172370496-7269cbb1-3b03-4763-840c-47ba3095ac58.png)

在这里卡了很长时间，一直没有响应，想请教一下是什么问题。

**Comment by iBobbyTS** [comment]
我自己没碰到过，手头也没有A100，你build我的包的时候有没有把A100的 compute compatibility加进去。
可以参考这篇博文 [PyTorch如何获得显卡 Compute Compatibility](https://blog.csdn.net/iBobbyTS/article/details/112074468)
或者这个Python代码
```
import torch
cc = torch.cuda.get_device_capability()
cc = f'{cc[0]}{cc[1]}'
print(cc)
```
把输出的cc填到下面{}的位置，A100我不确定是80还是82.
```
cd DAIN
python build.py -cc {}
```

另外VFIN是需要FFmpeg编解码的，你可以先试一下`ffmpeg -i ../731008375_nb2-1-80.flv ../731008375_nb2-1-80.mp4`，确定一下是不是FFmpeg的问题。

**Comment by Stardust-minus** [comment]
尝试了一下加80参数编译，没有效果。
视频成功用ffmpeg转了mp4，所以问题应该不在这。
之前尝试了上PyTorch 1.11.0是不会卡住的，但是会报错  RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method.
就很麻烦，感觉应该是和cuda版本有问题
